repos:
  - repo: local
    hooks:
      - id: pnpm-lint
        name: pnpm lint
        entry: pnpm lint
        language: system
        pass_filenames: false
        stages: [commit]
      - id: pnpm-build
        name: pnpm build
        entry: pnpm build
        language: system
        pass_filenames: false
        stages: [commit]
